export type FilterList = {
	type: string; // the type of the filter, for example "slot", "roulette", "provider", etc...
	categories: FilterCategory[]; // the categories of the filters, for example "provider", "type", "theme", etc... each category will have a list of filters that belong to that category, for example the "provider" category will have filters like "NetEnt", "Microgaming", etc...
};

export type FilterCategory = {
	name: string; // the name of the filter category, for example "provider", "type", "theme", etc...
	label: string; // the label of the filter category that will be shown to the users, for example "Provider", "Tipo", "Tema", etc... this is useful for localization and to make the gallery more user friendly, for example in the Italian locale we want to show "Provider" as "Fornitore", "Type" as "Tipo", etc...
	filters: Filter[]; // the list of filters that belong to this category, for example the "provider" category will have filters like "NetEnt", "Microgaming", etc... each filter will have a value and a title, the value is the value of the filter that will be used to filter the games in the gallery, for example "NetEnt", "Microgaming", etc... the title is the title of the filter that will be shown to the users, for example "NetEnt", "Microgaming", etc... this is useful for localization and to make the gallery more user friendly, for example in the Italian locale we want to show "NetEnt" as "NetEnt", "Microgaming" as "Microgaming", etc...
};

export type Filter = {
	value: string; // slug version of the filter that will be used to filter the games in the gallery, for example "netent", "microgaming", etc... this is useful for filtering the games in the gallery because we can use the value of the filter to filter the games in the gallery, for example if the user applies the "NetEnt" filter we will show only the games that have "netent" as provider, this is also useful for showing the filters in the filters panel, for example when we show the filters in the filters panel we will use the value of the filter to identify which filter is which, for example if we have a list of filters like this:
	title?: string; // the title of the filter that will be shown to the users, for example "NetEnt", "Microgaming", etc... this is useful for localization and to make the gallery more user friendly, for example in the Italian locale we want to show "NetEnt" as "NetEnt", "Microgaming" as "Microgaming", etc... this is also useful for showing the filters in the filters panel, for example when we show the filters in the filters panel we will show the title of the filter to the users, for example "NetEnt", "Microgaming", etc... and when the user applies a filter we will use the value of the filter to filter the games in the gallery, for example if the user applies the "NetEnt" filter we will show only the games that have "NetEnt" as provider
};
